# vim: set shiftwidth=2 softtabstop=2:

clone:
  hg:
    image: plugins/hg

pipeline:

  test:
    # TODO babel currency formatting change when using python:3 as base image;
    # "test_format_currency" then fails.
    image: xcgd/dronebase
    pull: true
    commands:

      # The following won't be needed once we switch to python:3 as base image.
      - apt  -qq update
      - DEBIAN_FRONTEND=noninteractive apt -qq -y install python3-dev
      - pip install setuptools --upgrade

      - pip install tox
      # tox only pycodestyle & py27 because python3 requires a genshi trunk from svn...
      - tox -e pycodestyle,py27

  notify:
    image: plugins/slack
    channel: dev
    username: drone
    secrets: [slack_webhook]
    when:
      status: [failure, success]
